[package]
name = "generate-range-of-integers"
version = "0.1.0"
authors = ["sigod <sigod.mail@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
